apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gogleapp-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gogleapp-test
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
